pipeline {
    agent any
    
    environment {
       muleRuntime = '4.3.0'
       appName_dev = 'multibranch-example-dev'
       appName_prod = 'multibranch-example-prod'
       worker_dev = '1'
       workerType_dev = 'MICRO'
       worker_prod = '1'
       workerType_prod = 'MICRO'
       region ='us-east-1'
       server = 'Anypoint'
       environment_prod = 'Production'
       environment_dev = 'Development'
       branch = 'dev'
    }

/*  
post {
    success {
      mail to: "XXXXX@gmail.com", 
      subject:"SUCCESS: ${currentBuild.fullDisplayName}", 
      body: "Build, we passed."
    }
    failure {
      mail to: "XXXXX@gmail.com", 
      subject:"FAILURE: ${currentBuild.fullDisplayName}", 
      body: "Boo, we failed."
    }
  }
*/


    stages {
    	stage('Checkout SCM') {
            steps {
             echo 'Checkout SCM.'
            }
        }

        stage('Build') {
            steps {
            echo 'Build.'
            }
        }
        
        stage('Unit Test') {
            steps {
            echo 'Unit Test'
               
            }
        }
 
         stage('Code Review') {
            steps {
            echo 'Code Review'
               
            }
        }
        
        stage('Deploy To Development Server') {
        	steps {
            echo 'Deploy To Development Server'
               
            }
        }
        stage('Copy to Nexus Repository') {
        	steps {
            echo 'Copy to Nexus Repository'
               
            }
        }
        
        stage('Deploy To Test Server') {
       
            steps {
                echo 'Deploying Application To Test'
            }
        }

        stage('Deploy To UAT/QA Test Server') {
       steps {
                echo 'Deploy To UAT/QA Test Server'
            }
        }
        
        stage('Deploy To Prod Server') {
         steps {
                echo 'Deploy To Prod Server'
            }
       
        }
    }
}